### ISSUE TITLE
re: testing transactions locally

### ISSUE THREAD

**Issue by stuarthalloway** [jacobobryant/trident#1]
Hi Jacob!

It is very exciting to see the work you are doing with Datomic and ions. Please feel free to reach out on the [forum](https://forum.datomic.com/) if you ever have questions.

One subtle point of transaction functions may confuse trident users: Datomic transaction functions operate on the in-transaction value of the database, so it is impossible to simulate them outside a transaction. [Running a transaction function locally](https://github.com/jacobobryant/trident/blob/128f49b86a5705a0cf81f8d95e0c50c2df5edccb/src/trident/datomic_cloud/client.clj#L17-L21) may be a development convenience, but the semantics are not the same.

We are working to reduce the need for transaction functions, and I would be curious to know where and when you have needed them in the past.

Best,
Stuart Halloway

**Comment by jacobobryant** [comment]
Thanks for stopping by! For local transaction functions--if I understand correctly, it is possible to simulate them outside the transactor if you ensure that:

1. no other transactions are sent to the transactor until after the transaction in question has had its transaction functions evaluated locally and has been sent to (and ran by) the transactor.
2. transaction functions are given the latest db value.

If you have only one machine running transactions (e.g. a development laptop), then using `locking` (as in the code you linked to) guarantees #&#x2060;1. I just realized that my code doesn't guarantee #&#x2060;2, but that could be fixed (e.g. with only one machine running transactions, just hold on to the value of `:db-after` when running transactions and use that).

I've been using transaction functions for authorization. I'm trying to create something like [Firebase security rules](https://firebase.google.com/docs/database/security) for Datomic. A few kinds of writes will need to be authorized atomically. For example, consider a chat group where:

1. participants can be either an admin or a normal user
2. admins can promote other participants to admins
3. the group must have at least one admin (so if you're the only admin and you want to leave the group, you have to promote someone else first).

The group has users A, B and C with A the admin. A submits a transaction that promotes B to admin and removes A from the group. At the same time, B submits a transaction that removes B from the group. If the transactions aren't authorized in a transaction function, then it's possible that both A and B will leave the group, and then the group will have no admin.

This scenario could be modeled in a way that doesn't require atomicity; but it seems likely to me that there are other scenarios which really do require atomicity (and thus tx functions). Although the authorization code I have now does all authorization in tx functions, I'm planning to make it so you can specify which (if any) authorization rules actually need to be ran in tx functions.
