### ISSUE TITLE
0.3.1 source code

### ISSUE THREAD

**Issue by mattiasarro** [jacobobryant/trident#11]
I'm reading biff source code, which refers to a function `trident.util/start-stystem` of trident/util version 0.3.1. Where could I find the source for this version?

**Comment by jacobobryant** [comment]
It's here: https://github.com/jacobobryant/trident/blob/db1187fa5f592c2c9489b3b0ee4d80af61263dfa/src/trident/util.cljc#L738

**Comment by jacobobryant** [comment]
I've added a tag for 0.3.1 as well. I'll get back in the habit of doing that to reduce confusion.

**Comment by mattiasarro** [comment]
Thank you @jacobobryant!
