### ISSUE TITLE
`refactor-nrepl` breaks on parsing borked trident artifact

### ISSUE THREAD

**Issue by jacobobryant** [jacobobryant/trident#4]
~also automatically trigger build on cljdoc?~
moved to #5 since this issue got hijacked

**Comment by taikhuu** [comment]
Hi, this lib got published to clojars with incorrect name and version, and it breaking refactor-nrepl when it trying to parse clojars libs.

**Comment by jacobobryant** [comment]
@taikhuu could you give me a little more information, e.g. a link to clojars, explain how it's breaking refactor-nrepl etc

**Comment by jacobobryant** [comment]
perhaps you're talking about this: https://clojars.org/trident/1.1
I'd be happy to remove that artifact but as far as I can tell, clojars doesn't allow that. It might be best to update refactor-nrepl so it doesn't break on unexpected input.

**Comment by benedekfazekas** [comment]
we looking into this on `refactor-nrepl` (see referenced issue). however, suppose for this case it would worth contacting the clojars maintainers if they could remove the messed up artifact.

**Comment by benedekfazekas** [comment]
You can either open an issue for this [here](https://github.com/clojars/clojars-web/issues) or contact @danielcompton directly.

**Comment by jacobobryant** [comment]
@benedekfazekas this situation does not meet clojar's [criteria for deletion](https://github.com/clojars/clojars-web/wiki/About#how-do-i-delete-a-jar):

> We will delete JARs for two reasons:
>
> - There is a security vulnerability in a published JAR, i.e. malicious code
> - Private credentials or code have been published

So updating `refactor-nrepl` would be the best option.

**Comment by danielcompton** [comment]
Yep, even if we were to delete this one artifact, nothing would stop people doing this kind of thing in the future.

**Comment by benedekfazekas** [comment]
this got solved thx to @andersenleo I will release a new version of `refactor-nrepl` with the fix in the evening. wonder if this possibly breaks other clojar clients tho...

**Comment by jacobobryant** [comment]
:+1: if it does, I'll be sure to point them to this thread.
